import { Car, DealershipSettings, Enquiry } from './types';

export const INITIAL_SETTINGS: DealershipSettings = {
  dealershipName: "Quality Used Cars",
  ownerName: "Syed Sabeer Riyaz",
  phone: "919999999999",
  whatsapp: "919999999999",
  email: "syed.ae018@gmail.com",
  location: "Bangalore, Karnataka, India",
  about: "Direct pre-owned car dealership operated by Syed Sabeer Riyaz. Verified vehicle history, transparent pricing, and honest buying with zero middleman commission."
};

export const INITIAL_ENQUIRIES: Enquiry[] = [];

export const INITIAL_INVENTORY: Car[] = [
  {
    id: "car-1",
    name: "Hyundai i20 Sportz (O) 1.2",
    brand: "Hyundai",
    model: "i20",
    variant: "Sportz (O) 1.2 Petrol",
    category: "Hatchbacks",
    price: "₹3,19,999",
    priceValue: 319999,
    year: 2014,
    fuel: "Petrol",
    transmission: "Manual",
    owners: "2nd Owner",
    kmDriven: "68,000 km",
    colour: "Metallic Grey",
    insurance: "Comprehensive Valid (Oct 2026)",
    fc: "Fitness Valid up to 2029",
    serviceHistory: "Authorized Hyundai Dealership Log",
    keys: "2 Original Keys with Remote",
    manual: "Owner Handbook & Toolkit Available",
    description: "Bangalore registered (KA-03). Clean executive hatchback with zero accident history. Pristine interior, alloy wheels, chilled climate control AC, reverse parking sensors, and new Michelin tyres.",
    status: "AVAILABLE",
    image: "/images/car-i20.jpg",
    images: [
      "/images/car-i20.jpg",
      "/images/hero-car.jpg"
    ],
    isFeatured: true,
    viewsCount: 42,
    whatsappClicks: 12,
    createdAt: "2026-08-25T10:00:00.000Z",
    updatedAt: "2026-08-27T01:00:00.000Z"
  },
  {
    id: "car-2",
    name: "Maruti Suzuki Ritz VXi ABS",
    brand: "Maruti Suzuki",
    model: "Ritz",
    variant: "VXi with ABS",
    category: "Under ₹3L",
    price: "₹2,49,999",
    priceValue: 249999,
    year: 2011,
    fuel: "Petrol",
    transmission: "Manual",
    owners: "2nd Owner",
    kmDriven: "54,000 km",
    colour: "Superior White",
    insurance: "Comprehensive Valid (Dec 2026)",
    fc: "FC Renewed Valid up to 2028",
    serviceHistory: "Regular Service Record Available",
    keys: "2 Keys with Maruti Remote",
    manual: "User Manual Available",
    description: "Bangalore registered (KA-05). Highly reliable K12 engine with superb city fuel economy. Smooth gearbox, power steering, 4 power windows, and clean non-smoker fabric seats.",
    status: "AVAILABLE",
    image: "/images/car-ritz.jpg",
    images: [
      "/images/car-ritz.jpg"
    ],
    isFeatured: true,
    viewsCount: 38,
    whatsappClicks: 9,
    createdAt: "2026-08-25T11:00:00.000Z",
    updatedAt: "2026-08-27T01:00:00.000Z"
  },
  {
    id: "car-3",
    name: "Hyundai i10 Sportz 1.2 Kappa",
    brand: "Hyundai",
    model: "i10",
    variant: "Sportz 1.2 Kappa2",
    category: "Under ₹3L",
    price: "₹1,99,999",
    priceValue: 199999,
    year: 2010,
    fuel: "Petrol",
    transmission: "Manual",
    owners: "2nd Owner",
    kmDriven: "62,000 km",
    colour: "Oyster Gold",
    insurance: "Third Party Valid",
    fc: "Fitness Certified up to 2027",
    serviceHistory: "Service Records Available",
    keys: "1 Original Key + 1 Spare",
    manual: "Available",
    description: "Bangalore registered (KA-05). Perfect compact family city car. Responsive Kappa 1.2 engine, very light clutch, front fog lamps, integrated 2-DIN audio system, and excellent suspension.",
    status: "AVAILABLE",
    image: "/images/car-i10.jpg",
    images: [
      "/images/car-i10.jpg"
    ],
    isFeatured: false,
    viewsCount: 29,
    whatsappClicks: 7,
    createdAt: "2026-08-25T12:00:00.000Z",
    updatedAt: "2026-08-27T01:00:00.000Z"
  },
  {
    id: "car-4",
    name: "Toyota Innova 2.5 VX 7-Seater",
    brand: "Toyota",
    model: "Innova",
    variant: "2.5 VX (7 Seater Captain Seats)",
    category: "SUVs",
    price: "₹9,75,000",
    priceValue: 975000,
    year: 2013,
    fuel: "Diesel",
    transmission: "Manual",
    owners: "2nd Owner",
    kmDriven: "1,24,000 km",
    colour: "Silver Metallic",
    insurance: "Comprehensive Valid (Nov 2026)",
    fc: "Fitness Valid up to 2028",
    serviceHistory: "Toyota Dealership History Documented",
    keys: "2 Original Remote Keys",
    manual: "Complete Toyota Documentation Pack",
    description: "Bangalore registered (KA-04). Legendary bulletproof D-4D diesel engine. Top VX variant with middle row captain seats, dual AC with roof vents, touchscreen infotainment, and unmatched long-drive comfort.",
    status: "AVAILABLE",
    image: "/images/car-innova.jpg",
    images: [
      "/images/car-innova.jpg"
    ],
    isFeatured: true,
    viewsCount: 56,
    whatsappClicks: 16,
    createdAt: "2026-08-25T13:00:00.000Z",
    updatedAt: "2026-08-27T01:00:00.000Z"
  },
  {
    id: "car-5",
    name: "Honda City 1.5 V i-VTEC",
    brand: "Honda",
    model: "City",
    variant: "1.5 V i-VTEC Sedan",
    category: "Sedans",
    price: "₹5,45,000",
    priceValue: 545000,
    year: 2015,
    fuel: "Petrol",
    transmission: "Manual",
    owners: "1st Owner",
    kmDriven: "72,000 km",
    colour: "Urban Titanium",
    insurance: "Comprehensive Bumper-to-Bumper Valid",
    fc: "Fitness Valid up to 2030",
    serviceHistory: "Full Authorized Honda Service History",
    keys: "2 Smart Keys with Push Button Start",
    manual: "Complete Documentation Available",
    description: "Bangalore registered (KA-01). Single owner executive luxury sedan. Premium cabin, cruise control, steering-mounted audio, rear AC vents, electric folding mirrors, and silky smooth 1.5 i-VTEC engine.",
    status: "AVAILABLE",
    image: "/images/car-hero-i20.jpg",
    images: [
      "/images/car-hero-i20.jpg"
    ],
    isFeatured: false,
    viewsCount: 34,
    whatsappClicks: 8,
    createdAt: "2026-08-25T14:00:00.000Z",
    updatedAt: "2026-08-27T01:00:00.000Z"
  },
  {
    id: "car-6",
    name: "Maruti Suzuki Swift Dzire VDi",
    brand: "Maruti Suzuki",
    model: "Swift Dzire",
    variant: "VDi 1.3 DDiS Diesel",
    category: "Sedans",
    price: "₹3,85,000",
    priceValue: 385000,
    year: 2014,
    fuel: "Diesel",
    transmission: "Manual",
    owners: "2nd Owner",
    kmDriven: "81,000 km",
    colour: "Silky Silver",
    insurance: "Comprehensive Valid (Jan 2027)",
    fc: "Fitness Valid up to 2029",
    serviceHistory: "Authorized Maruti Workshop Maintained",
    keys: "2 Keys with Remote",
    manual: "Owner Handbook Available",
    description: "Bangalore registered (KA-51). Incredible fuel economy of 22+ km/l. Chilled AC, smooth clutch, new battery with warranty, Pioneer sound system, and zero mechanical issues.",
    status: "AVAILABLE",
    image: "/images/car-ritz.jpg",
    images: [
      "/images/car-ritz.jpg"
    ],
    isFeatured: false,
    viewsCount: 47,
    whatsappClicks: 11,
    createdAt: "2026-08-25T15:00:00.000Z",
    updatedAt: "2026-08-27T01:00:00.000Z"
  }
];
